# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=120, unique=True)),
                ('rating', models.SmallIntegerField(default=0, unique=True)),
            ],
        ),
    ]
