# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
